namespace DevExpress.DXperience.Demos.CodeDemo
{
    using System;

    internal static class StringContainer
    {
        internal static string ExampleMethod = "/* ExampleMethod */";
        internal static string NameSpace = "/* NameSpace */";
        internal static string NestedClasses = "/* NestedClasses */";
        internal static string NestedStringToReplace = "/* NestedStringToReplace */";
        internal static string RegionExampleCodeName = "/* RegionExampleCodeName */";
        internal static string SetUp = "/* SetUpCode */";
        internal static string SLNString = "\r\n\r\nMicrosoft Visual Studio Solution File, Format Version 12.00\r\n# Visual Studio 2013\r\nVisualStudioVersion = 12.0.31101.0\r\nMinimumVisualStudioVersion = 10.0.40219.1\r\nProject(\"{//GUIDSLN}\") = \"DxSample\", \"DxSample.#csprojOrvbprog\", \"{//GUIDCSproj}\"\r\nEndProject\r\nGlobal\r\n\tGlobalSection(SolutionConfigurationPlatforms) = preSolution\r\n\t\tDebug|Any CPU = Debug|Any CPU\r\n\t\tRelease|Any CPU = Release|Any CPU\r\n\tEndGlobalSection\r\n\tGlobalSection(ProjectConfigurationPlatforms) = postSolution\r\n\t\t{//GUIDCSproj}.Debug|Any CPU.ActiveCfg = Debug|Any CPU\r\n\t\t{//GUIDCSproj}.Debug|Any CPU.Build.0 = Debug|Any CPU\r\n\t\t{//GUIDCSproj}.Release|Any CPU.ActiveCfg = Release|Any CPU\r\n\t\t{//GUIDCSproj}.Release|Any CPU.Build.0 = Release|Any CPU\r\n\tEndGlobalSection\r\n\tGlobalSection(SolutionProperties) = preSolution\r\n\t\tHideSolutionNode = FALSE\r\n\tEndGlobalSection\r\nEndGlobal\r\n\r\n";
        internal static string TearDown = "/* TearDownCode */";
        internal static string UserControlCSCode = (Usings + Environment.NewLine + "namespace " + NameSpace + " {" + Environment.NewLine + new string(' ', 4) + "public partial class " + UserControlName + " : XtraUserControl {" + Environment.NewLine + new string(' ', 8) + "public " + UserControlName + "() {" + Environment.NewLine + new string(' ', 12) + "InitializeComponent();" + Environment.NewLine + new string(' ', 12) + "#region SetUp" + Environment.NewLine + SetUp + new string(' ', 12) + "#endregion SetUp" + Environment.NewLine + Environment.NewLine + new string(' ', 12) + "#region #" + RegionExampleCodeName + Environment.NewLine + ExampleMethod + new string(' ', 12) + "#endregion #" + RegionExampleCodeName + Environment.NewLine + new string(' ', 8) + "}" + Environment.NewLine + new string(' ', 8) + "#region CleanUp" + Environment.NewLine + new string(' ', 8) + "void OnDisposing() {" + Environment.NewLine + TearDown + new string(' ', 8) + "}" + Environment.NewLine + new string(' ', 8) + "#endregion CleanUp" + Environment.NewLine + NestedClasses + new string(' ', 4) + "}" + Environment.NewLine + "}");
        internal static string UserControlDesignerCSCode = ("namespace " + NameSpace + " {\r\n    partial class " + UserControlName + " {\r\n        /// <summary> \r\n        /// Required designer variable.\r\n        /// </summary>\r\n        private System.ComponentModel.IContainer components = null;\r\n\r\n        /// <summary> \r\n        /// Clean up any resources being used.\r\n        /// </summary>\r\n        /// <param name=\"disposing\">true if managed resources should be disposed; otherwise, false.</param>\r\n        protected override void Dispose(bool disposing) {\r\n            if(disposing && (components != null)) {\r\n                OnDisposing();\r\n                components.Dispose();\r\n            }\r\n            base.Dispose(disposing);\r\n        }\r\n\r\n        #region Component Designer generated code\r\n\r\n        /// <summary> \r\n        /// Required method for Designer support - do not modify \r\n        /// the contents of this method with the code editor.\r\n        /// </summary>\r\n        private void InitializeComponent() {\r\n            components = new System.ComponentModel.Container();\r\n            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;\r\n        }\r\n\r\n        #endregion\r\n    }\r\n}");
        internal static string UserControlDesignerVBCode = ("Namespace " + NameSpace + "\r\n    Partial Class " + UserControlName + "\r\n\r\n        'UserControl overrides dispose to clean up the component list.\r\n        <System.Diagnostics.DebuggerNonUserCode()> _\r\n        Protected Overrides Sub Dispose(ByVal disposing As Boolean)\r\n            Try\r\n                If disposing AndAlso components IsNot Nothing Then\r\n                    OnDisposing()\r\n                    components.Dispose()\r\n                End If\r\n            Finally\r\n                MyBase.Dispose(disposing)\r\n            End Try\r\n        End Sub\r\n\r\n        'Required by the Windows Form Designer\r\n        Private components As System.ComponentModel.IContainer\r\n\r\n        'NOTE: The following procedure is required by the Windows Form Designer\r\n        'It can be modified using the Windows Form Designer.  \r\n        'Do not modify it using the code editor.\r\n        <System.Diagnostics.DebuggerStepThrough()> _\r\n        Private Sub InitializeComponent()\r\n            components = New System.ComponentModel.Container()\r\n            Me.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font\r\n        End Sub\r\n    End Class\r\nEnd Namespace");
        internal static string UserControlName = "/* UserControlName */";
        internal static string UserControlVBCode = (Usings + Environment.NewLine + "Namespace " + NameSpace + Environment.NewLine + new string(' ', 4) + "Partial Public Class " + UserControlName + Environment.NewLine + new string(' ', 8) + "Inherits DevExpress.XtraEditors.XtraUserControl" + Environment.NewLine + new string(' ', 8) + "Public Sub New() " + Environment.NewLine + new string(' ', 12) + "InitializeComponent()" + Environment.NewLine + SetUp + Environment.NewLine + ExampleMethod + new string(' ', 8) + "End Sub" + Environment.NewLine + new string(' ', 8) + " Private Sub OnDisposing()" + Environment.NewLine + TearDown + new string(' ', 8) + "End Sub" + Environment.NewLine + NestedClasses + new string(' ', 4) + "\tEnd Class" + Environment.NewLine + "End Namespace");
        internal static string Usings = "/* Usings */";
    }
}

